# Site settings
title: IPAC '16
email: admin@ipac16.or
description: > # this means to ignore newlines until "baseurl:"
  7th International Particle Accelerator Conference | IPAC '16 | Busan, Korea
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ipac16.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
